Create models
Abel-desu/Blog-App pull request #2
Opened 2022-10-07 21:49 UTC by Abel-desu

- Create models
- Use models to insert data
- Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.
- Create custom methods

2022-10-07 22:00 UTC, tufoinnkuo10 requested changes
## Hi @Abel-desu 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


## Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-07 22:00 UTC, tufoinnkuo10 commented on app/models/user.rb
>  end
- [ ] please kindly add in the user model a method that returns 3 most recent posts
eg 
```ruby
def recent_post
  posts.order('created_at Desc').limit(3)
end
```

2022-10-07 22:00 UTC, tufoinnkuo10 commented on app/models/post.rb
> +end
- [ ] please add to the post model a method that updates the posts counter for a user

2022-10-07 22:00 UTC, tufoinnkuo10 commented on app/models/post.rb
> +  has_many :likes, foreign_key: :post_id, dependent: :destroy
- [ ] please add to the post model a method that returns the 5 most recent comments for a given post
eg
```ruby
def recent_comments
  comments.order('created_at Desc').limit(5)
end
```

2022-10-07 22:00 UTC, tufoinnkuo10 commented on app/models/comment.rb
>  end
- [ ] kindly ensure the comment model has a method that updates the comments counter for a post

2022-10-07 22:00 UTC, tufoinnkuo10 commented on app/models/like.rb
> +  belongs_to :post
- [ ] please add to the like model a method that updates the likes counter for a post
eg
```ruby
def update_likes_counter
  post.increment!(:likes_counter)
end
```

2022-10-08 08:47 UTC, AnselemOdims requested changes
### Hi @Abel-desu , 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-10-08 08:47 UTC, AnselemOdims commented on app/models/like.rb
>  end
- [ ] As pointed out by the previous reviewer, please kindly include a method that updates the likes counter.

2022-10-08 09:05 UTC, AnselemOdims approved these changes
### Hi  @Abel-desu 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 15:33 UTC, merged